/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geneticosParalelos;

import Hilo.Parametros;
import geneticos.GeneticoSAT;
import objetos.Matriz;

/**
 *
 * @author Vanessa
 */
public class Gestor extends javax.swing.JFrame {
    private int numeroGenetico=0;
    /**
     * Creates new form Gestor
     */
    public Gestor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crearNuevoGeneticoBtn = new javax.swing.JButton();
        tipoGenetico = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        crearNuevoGeneticoBtn.setText("Crear");
        crearNuevoGeneticoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearNuevoGeneticoBtnActionPerformed(evt);
            }
        });

        tipoGenetico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Binario", "Reinas", "SAT", "TSP", "Tipo" }));
        tipoGenetico.setSelectedIndex(4);
        tipoGenetico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoGeneticoActionPerformed(evt);
            }
        });

        jLabel1.setText("Crear nuevo genético");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(tipoGenetico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(crearNuevoGeneticoBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel1)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoGenetico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crearNuevoGeneticoBtn))
                .addContainerGap(181, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoGeneticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoGeneticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoGeneticoActionPerformed

    private void crearNuevoGeneticoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearNuevoGeneticoBtnActionPerformed
        //PRESIONAR EL BOTON
        if(this.tipoGenetico.getSelectedIndex()==0){ //Binario
            
        } else if(this.tipoGenetico.getSelectedIndex()==1){ //Reinas
            
        } else if(this.tipoGenetico.getSelectedIndex()==2){ //SAT
            Matriz.matriz=Matriz.leerArchivo(1); //0: TSP, 1: SB
            
            String titulo= ("Genetico " + this.numeroGenetico);
            Consola c = new Consola(titulo);
            GeneticoSAT genetico = new GeneticoSAT(900, 100000000, 0, 0, 0, 0, 0, 100, c);
            
            Parametros p = new Parametros(genetico, titulo);
            this.numeroGenetico++;
            p.setVisible(true);
            
        }else{ //TSP
            
        }
    }//GEN-LAST:event_crearNuevoGeneticoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crearNuevoGeneticoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> tipoGenetico;
    // End of variables declaration//GEN-END:variables
}
