/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geneticosParalelos;

import Hilo.Parametros;
import geneticos.GeneticoBinario;
import geneticos.GeneticoReinas;
import geneticos.GeneticoSAT;
import geneticos.GeneticoTSP;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Arrays;
import objetos.Matriz;

/**
 *
 * @author Vanessa
 */
public class Gestor extends javax.swing.JFrame {
    private int numeroGenetico=0;
    private boolean banderaPrimerGenetico = false;
    private ArrayList<GeneticoSAT> geneticosSAT;
    private ArrayList<GeneticoTSP> geneticosTSP;
    private ArrayList<GeneticoBinario> geneticosBinario;
    private ArrayList<GeneticoReinas> geneticosReinas;
    private ArrayList<Parametros> parametros;
    private int seleccion;
    //Binario=0, Reinas=1, SAT=2, TSP=3
    /**
     * Creates new form Gestor
     */
    public Gestor() {
        this.geneticosSAT = new ArrayList<GeneticoSAT>();
        this.geneticosTSP = new ArrayList<GeneticoTSP>();
        this.geneticosBinario = new ArrayList<GeneticoBinario>();
        this.geneticosReinas = new ArrayList<GeneticoReinas>();
        this.parametros = new ArrayList<Parametros>();
        super.setTitle("Gestor");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        crearNuevoGeneticoBtn = new javax.swing.JButton();
        tipoGenetico = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        geneticoCambiarParametros1 = new javax.swing.JComboBox<>();
        geneticoCambiarParametros2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        geneticoCambiarMejor1 = new javax.swing.JComboBox<>();
        geneticoCambiarMejor2 = new javax.swing.JComboBox<>();
        btnCambiarParametros = new javax.swing.JButton();
        btnCambiarMejor = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cerrarGenetico = new javax.swing.JComboBox<>();
        btnCerrarGenetico = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        crearNuevoGeneticoBtn.setText("Crear");
        crearNuevoGeneticoBtn.setMaximumSize(new java.awt.Dimension(59, 25));
        crearNuevoGeneticoBtn.setMinimumSize(new java.awt.Dimension(59, 25));
        crearNuevoGeneticoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearNuevoGeneticoBtnActionPerformed(evt);
            }
        });

        tipoGenetico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Binario", "Reinas", "SAT", "TSP", "Tipo" }));
        tipoGenetico.setSelectedIndex(4);
        tipoGenetico.setMaximumSize(new java.awt.Dimension(78, 25));
        tipoGenetico.setMinimumSize(new java.awt.Dimension(78, 25));
        tipoGenetico.setPreferredSize(new java.awt.Dimension(78, 25));
        tipoGenetico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoGeneticoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Crear nuevo genético");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Cambiar parámetros entre genéticos");

        geneticoCambiarParametros1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Genético" }));
        geneticoCambiarParametros1.setMaximumSize(new java.awt.Dimension(135, 25));
        geneticoCambiarParametros1.setMinimumSize(new java.awt.Dimension(135, 25));
        geneticoCambiarParametros1.setPreferredSize(new java.awt.Dimension(135, 25));
        geneticoCambiarParametros1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geneticoCambiarParametros1ActionPerformed(evt);
            }
        });

        geneticoCambiarParametros2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Genético" }));
        geneticoCambiarParametros2.setMaximumSize(new java.awt.Dimension(135, 25));
        geneticoCambiarParametros2.setMinimumSize(new java.awt.Dimension(135, 25));
        geneticoCambiarParametros2.setPreferredSize(new java.awt.Dimension(135, 25));

        jLabel3.setText("a");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Cambiar mejor individuo entre geneticos");

        geneticoCambiarMejor1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Genético" }));
        geneticoCambiarMejor1.setMaximumSize(new java.awt.Dimension(135, 25));
        geneticoCambiarMejor1.setMinimumSize(new java.awt.Dimension(135, 25));
        geneticoCambiarMejor1.setPreferredSize(new java.awt.Dimension(135, 25));

        geneticoCambiarMejor2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Genético" }));
        geneticoCambiarMejor2.setMaximumSize(new java.awt.Dimension(135, 25));
        geneticoCambiarMejor2.setMinimumSize(new java.awt.Dimension(135, 25));
        geneticoCambiarMejor2.setPreferredSize(new java.awt.Dimension(135, 25));

        btnCambiarParametros.setText("Cambiar");
        btnCambiarParametros.setMaximumSize(new java.awt.Dimension(80, 25));
        btnCambiarParametros.setMinimumSize(new java.awt.Dimension(80, 25));
        btnCambiarParametros.setPreferredSize(new java.awt.Dimension(80, 25));
        btnCambiarParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarParametrosActionPerformed(evt);
            }
        });

        btnCambiarMejor.setText("Cambiar");
        btnCambiarMejor.setMaximumSize(new java.awt.Dimension(80, 25));
        btnCambiarMejor.setMinimumSize(new java.awt.Dimension(80, 25));
        btnCambiarMejor.setPreferredSize(new java.awt.Dimension(80, 25));
        btnCambiarMejor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarMejorActionPerformed(evt);
            }
        });

        jLabel5.setText("a");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Cerrar genético");

        cerrarGenetico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Genético" }));
        cerrarGenetico.setMaximumSize(new java.awt.Dimension(135, 25));
        cerrarGenetico.setMinimumSize(new java.awt.Dimension(135, 25));
        cerrarGenetico.setPreferredSize(new java.awt.Dimension(135, 25));

        btnCerrarGenetico.setText("Cerrar");
        btnCerrarGenetico.setMaximumSize(new java.awt.Dimension(63, 25));
        btnCerrarGenetico.setMinimumSize(new java.awt.Dimension(63, 25));
        btnCerrarGenetico.setPreferredSize(new java.awt.Dimension(63, 25));
        btnCerrarGenetico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarGeneticoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tipoGenetico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(crearNuevoGeneticoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(125, 125, 125))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(geneticoCambiarParametros1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(geneticoCambiarParametros2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(geneticoCambiarMejor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(geneticoCambiarMejor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(btnCerrarGenetico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(cerrarGenetico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btnCambiarParametros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCambiarMejor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoGenetico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crearNuevoGeneticoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(geneticoCambiarParametros1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(geneticoCambiarParametros2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCambiarParametros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(geneticoCambiarMejor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geneticoCambiarMejor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCambiarMejor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(cerrarGenetico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrarGenetico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoGeneticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoGeneticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoGeneticoActionPerformed

    private void crearNuevoGeneticoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearNuevoGeneticoBtnActionPerformed
        //PRESIONAR EL BOTON
        
        if(this.banderaPrimerGenetico==false){ //Solo la primera vez que se seleccione un genético
            seleccion = this.tipoGenetico.getSelectedIndex();
            banderaPrimerGenetico=true;
            String aux = this.tipoGenetico.getItemAt(seleccion);
            this.tipoGenetico.removeAllItems();
            this.tipoGenetico.addItem(aux);
            
        }
        switch(seleccion){ //tipo de genetico
            case 0:
                nuevoGeneticoBinario();
                break;
            case 1:
                nuevoGeneticoReinas();
                break;
            case 2:
                nuevoGeneticoSAT();
                break;
            default :
                nuevoGeneticoTSP();
                break;
        }
    }//GEN-LAST:event_crearNuevoGeneticoBtnActionPerformed

    private void agregarItems(String titulo) {
        this.geneticoCambiarMejor1.addItem(titulo);
        this.geneticoCambiarMejor2.addItem(titulo);
        this.geneticoCambiarParametros1.addItem(titulo);
        this.geneticoCambiarParametros2.addItem(titulo);
        this.cerrarGenetico.addItem(titulo);
    }
    private void borrarItems(int index) {
        this.geneticoCambiarMejor1.removeItemAt(index);//remove(index);
        this.geneticoCambiarMejor2.removeItemAt(index);
        this.geneticoCambiarParametros1.removeItemAt(index);
        this.geneticoCambiarParametros2.removeItemAt(index);
        this.cerrarGenetico.removeItemAt(index);
    }
    private void agregarItemsGeneticos() {
        this.tipoGenetico.removeAllItems();
        this.tipoGenetico.setSelectedItem(4);
        this.tipoGenetico.addItem("Binario");
        this.tipoGenetico.addItem("Reinas");
        this.tipoGenetico.addItem("SAT");
        this.tipoGenetico.addItem("TSP");
        this.tipoGenetico.addItem("Tipo");
        
    }
    
    private void btnCambiarParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarParametrosActionPerformed
        //CAMBIAR PARAMETROS ENTRE GENETICOS
        //Binario=0, Reinas=1, SAT=2, TSP=3
        int seleccion1 = this.geneticoCambiarParametros1.getSelectedIndex()-1;
        int seleccion2 = this.geneticoCambiarParametros2.getSelectedIndex()-1;
        //A seleccion2 le mandamos lo de seleccion1
        if(seleccion1 != seleccion2 && seleccion1>=0 && seleccion2>=0){
            switch(seleccion){ //tipo de genetico
                case 0:
                    GeneticoBinario aux3 = this.geneticosBinario.get(seleccion1);
                    this.geneticosBinario.get(seleccion2).cambiarParametros(aux3.getTamanioPoblacion(), aux3.getProbabilidadMuta(), aux3.getSeleccionMadre(), aux3.getSeleccionPadre(), aux3.getTipoMuestreo(), aux3.getPorcentajeMuestreo());
                    break;
                case 1:
                    GeneticoReinas aux2 = this.geneticosReinas.get(seleccion1);
                    this.geneticosReinas.get(seleccion2).cambiarParametros(aux2.getTamanioPoblacion(), aux2.getProbabilidadMuta(), aux2.getSeleccionMadre(), aux2.getSeleccionPadre(), aux2.getTipoMuestreo(), aux2.getPorcentajeMuestreo());
                    break;
                case 2:
                    GeneticoSAT aux = this.geneticosSAT.get(seleccion1);
                    this.geneticosSAT.get(seleccion2).cambiarParametros(aux.getTamanioPoblacion(), aux.getProbabilidadMuta(), aux.getSeleccionMadre(), aux.getSeleccionPadre(), aux.getTipoMuestreo(), aux.getPorcentajeMuestreo());
                    break;
                default :
                    GeneticoTSP aux1 = this.geneticosTSP.get(seleccion1);
                    this.geneticosTSP.get(seleccion2).cambiarParametros(aux1.getTamanioPoblacion(), aux1.getProbabilidadMuta(), aux1.getSeleccionMadre(), aux1.getSeleccionPadre(), aux1.getTipoMuestreo(), aux1.getPorcentajeMuestreo());
                    break;
            }
            this.parametros.get(seleccion2).actualizarValores();
        }
    }//GEN-LAST:event_btnCambiarParametrosActionPerformed

    private void btnCambiarMejorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarMejorActionPerformed
        //MANDAT MEJOR INDIVISUO DE UN GENETICO A OTRO
        //Binario=0, Reinas=1, SAT=2, TSP=3
        int seleccion1 = this.geneticoCambiarMejor1.getSelectedIndex()-1;
        int seleccion2 = this.geneticoCambiarMejor2.getSelectedIndex()-1;
        //A seleccion2 le mandamos lo de seleccion1
        if(seleccion1 != seleccion2 && seleccion1>=0 && seleccion2>=0){
            switch(seleccion){ //tipo de genetico
                case 0:
                    GeneticoBinario aux1 = this.geneticosBinario.get(seleccion1);
                    this.geneticosBinario.get(seleccion2).setMejorIndividuo(aux1.getMejorIndividuo());
                    break;
                case 1:
                    GeneticoReinas aux2 = this.geneticosReinas.get(seleccion1);
                    this.geneticosReinas.get(seleccion2).setMejorIndividuo(aux2.getMejorIndividuo());
                    break;
                case 2:
                    GeneticoSAT aux3 = this.geneticosSAT.get(seleccion1);
                    this.geneticosSAT.get(seleccion2).setMejorIndividuo(aux3.getMejorIndividuo());
                    break;
                default :
                    GeneticoTSP aux4 = this.geneticosTSP.get(seleccion1);
                    this.geneticosTSP.get(seleccion2).setMejorIndividuo(aux4.getMejorIndividuo());
                    
                    break;
            }
        }
    }//GEN-LAST:event_btnCambiarMejorActionPerformed

    private void geneticoCambiarParametros1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geneticoCambiarParametros1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_geneticoCambiarParametros1ActionPerformed

    private void btnCerrarGeneticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarGeneticoActionPerformed
        int seleccionCerrar = this.cerrarGenetico.getSelectedIndex()-1;
        //Binario=0, Reinas=1, SAT=2, TSP=3
        if(seleccionCerrar>=0){
          switch(seleccion){ //tipo de genetico
                case 0:
                    this.geneticosBinario.get(seleccionCerrar).consola.dispose();
                    this.geneticosBinario.remove(seleccionCerrar);
                    break;
                case 1:
                    this.geneticosReinas.get(seleccionCerrar).consola.dispose();
                    this.geneticosReinas.remove(seleccionCerrar);
                    break;
                case 2:
                    //this.geneticosSAT.get(seleccionCerrar).consola.setVisible(false);
                    this.geneticosSAT.get(seleccionCerrar).consola.dispose();
                    this.geneticosSAT.remove(seleccionCerrar);
                    break;
                default :
                    this.geneticosTSP.get(seleccionCerrar).consola.dispose();
                    this.geneticosTSP.remove(seleccionCerrar);
                    break;
            }
        //this.parametros.get(seleccionCerrar).setVisible(false);
        this.parametros.get(seleccionCerrar).dispose();
        this.parametros.remove(seleccionCerrar);
        this.borrarItems(seleccionCerrar+1);  
        this.numeroGenetico--;
            if(this.numeroGenetico==0){
                banderaPrimerGenetico = false;
                agregarItemsGeneticos();
            }
        }
        
    }//GEN-LAST:event_btnCerrarGeneticoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarMejor;
    private javax.swing.JButton btnCambiarParametros;
    private javax.swing.JButton btnCerrarGenetico;
    private javax.swing.JComboBox<String> cerrarGenetico;
    private javax.swing.JButton crearNuevoGeneticoBtn;
    private javax.swing.JComboBox<String> geneticoCambiarMejor1;
    private javax.swing.JComboBox<String> geneticoCambiarMejor2;
    private javax.swing.JComboBox<String> geneticoCambiarParametros1;
    private javax.swing.JComboBox<String> geneticoCambiarParametros2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> tipoGenetico;
    // End of variables declaration//GEN-END:variables

    private void nuevoGeneticoBinario() {
        String titulo= ("Genetico Binario " + this.numeroGenetico);
        Consola c = new Consola(titulo);
        boolean usandoClasificador = true;
        this.geneticosBinario.add(this.numeroGenetico, new GeneticoBinario(10000, 100000000, 0, 0, 0, 0, 0, c, usandoClasificador ));
        //(tamanioPoblacion, numeroGeneraciones, probabilidadMuta, seleM, seleP, tipoMuestreo, muestreo, consola);
        this.parametros.add(this.numeroGenetico, new Parametros(this.geneticosBinario.get(this.numeroGenetico), titulo));
        agregarItems(titulo);
        this.parametros.get(this.numeroGenetico).setVisible(true);
        this.numeroGenetico++;
    }

    private void nuevoGeneticoReinas() {
        String titulo= ("Genetico Reinas " + this.numeroGenetico);
        Consola c = new Consola(titulo);
        int tamanioTablero=8;
        this.geneticosReinas.add(this.numeroGenetico, new GeneticoReinas(10000, 100000000, 0, 0, 0, 0, 0, tamanioTablero, c));
        //(tamanioPoblacion, numeroGeneraciones, probabilidadMuta, seleM, seleP, tipoMuestreo, muestreo, consola);
        this.parametros.add(this.numeroGenetico, new Parametros(this.geneticosReinas.get(this.numeroGenetico), titulo));
        agregarItems(titulo);
        this.parametros.get(this.numeroGenetico).setVisible(true);
        this.numeroGenetico++;
    }

    private void nuevoGeneticoSAT() {
        Matriz.matriz=Matriz.leerArchivo(1); //0: TSP, 1: SB
        String titulo= ("Genetico SAT " + this.numeroGenetico);
        Consola c = new Consola(titulo);
        this.geneticosSAT.add(this.numeroGenetico, new GeneticoSAT(900, 100000000, 0, 0, 0, 0, 0, 100, c));
        //tamaño de pobleación, num Generaciones, cuidad inicial o tamaño de tabl, 
        //prob Muta, seleccion para madre y padre, tipo de muestreo y tamaño de muestreo
        this.parametros.add(this.numeroGenetico, new Parametros(this.geneticosSAT.get(this.numeroGenetico), titulo));
        agregarItems(titulo);
        this.parametros.get(this.numeroGenetico).setVisible(true);
        this.numeroGenetico++;
    }

    private void nuevoGeneticoTSP() {
        Matriz.matriz=Matriz.leerArchivo(0); //0: TSP, 1: SB
        String titulo= ("Genetico TSP " + this.numeroGenetico);
        Consola c = new Consola(titulo);
        this.geneticosTSP.add(this.numeroGenetico, new GeneticoTSP(500, 100000000, 0, 0, 0, 0, 0, c));
        //int tamanioPoblacion, int numeroGeneraciones, double probabilidadMuta, int seleM, int seleP, int tipoMuestreo, float muestreo, Consola consola
        this.parametros.add(this.numeroGenetico, new Parametros(this.geneticosTSP.get(this.numeroGenetico), titulo));
        agregarItems(titulo);
        this.parametros.get(this.numeroGenetico).setVisible(true);
        this.numeroGenetico++;
    }

}
