/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geneticosParalelos;

import Hilo.Parametros;
import geneticos.GeneticoBinario;
import geneticos.GeneticoReinas;
import geneticos.GeneticoSAT;
import geneticos.GeneticoTSP;
import java.util.ArrayList;
import java.util.Arrays;
import objetos.Matriz;

/**
 *
 * @author Vanessa
 */
public class Gestor extends javax.swing.JFrame {
    private int numeroGenetico=0;
    private boolean bandera = false;
    private ArrayList<GeneticoSAT> geneticosSAT;
    private ArrayList<GeneticoTSP> geneticosTSP;
    private ArrayList<GeneticoBinario> geneticosBinario;
    private ArrayList<GeneticoReinas> geneticosReinas;
    private ArrayList<Parametros> parametros;
    private int seleccion;
    //Binario=0, Reinas=1, SAT=2, TSP=3
    /**
     * Creates new form Gestor
     */
    public Gestor() {
        this.geneticosSAT = new ArrayList<GeneticoSAT>();
        this.geneticosTSP = new ArrayList<GeneticoTSP>();
        this.geneticosBinario = new ArrayList<GeneticoBinario>();
        this.geneticosReinas = new ArrayList<GeneticoReinas>();
        this.parametros = new ArrayList<Parametros>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crearNuevoGeneticoBtn = new javax.swing.JButton();
        tipoGenetico = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        geneticoCambiarParametros1 = new javax.swing.JComboBox<>();
        geneticoCambiarParametros2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        geneticoCambiarMejor1 = new javax.swing.JComboBox<>();
        geneticoCambiarMejor2 = new javax.swing.JComboBox<>();
        btnIntercambiarParametros = new javax.swing.JButton();
        btnIntercambiarMejor = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        crearNuevoGeneticoBtn.setText("Crear");
        crearNuevoGeneticoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearNuevoGeneticoBtnActionPerformed(evt);
            }
        });

        tipoGenetico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Binario", "Reinas", "SAT", "TSP", "Tipo" }));
        tipoGenetico.setSelectedIndex(4);
        tipoGenetico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoGeneticoActionPerformed(evt);
            }
        });

        jLabel1.setText("Crear nuevo genético");

        jLabel2.setText("Cambiar parámetros entre genéticos");

        geneticoCambiarParametros1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Genético" }));

        geneticoCambiarParametros2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Genético" }));

        jLabel3.setText("a");

        jLabel4.setText("Cambiar mejor individuo entre geneticos");

        geneticoCambiarMejor1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Genético" }));

        geneticoCambiarMejor2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Genético" }));

        btnIntercambiarParametros.setText("Cambiar");
        btnIntercambiarParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntercambiarParametrosActionPerformed(evt);
            }
        });

        btnIntercambiarMejor.setText("Cambiar");
        btnIntercambiarMejor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntercambiarMejorActionPerformed(evt);
            }
        });

        jLabel5.setText("a");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(geneticoCambiarParametros1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(geneticoCambiarParametros2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(geneticoCambiarMejor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(46, 46, 46)
                        .addComponent(geneticoCambiarMejor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(tipoGenetico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(crearNuevoGeneticoBtn)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnIntercambiarParametros)
                                .addGap(91, 91, 91))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnIntercambiarMejor)
                                .addGap(88, 88, 88))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel1)))
                        .addGap(39, 39, 39)))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearNuevoGeneticoBtn)
                    .addComponent(tipoGenetico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(geneticoCambiarParametros2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geneticoCambiarParametros1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIntercambiarParametros)
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(geneticoCambiarMejor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(geneticoCambiarMejor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnIntercambiarMejor)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoGeneticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoGeneticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoGeneticoActionPerformed

    private void crearNuevoGeneticoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearNuevoGeneticoBtnActionPerformed
        //PRESIONAR EL BOTON
        if(this.bandera==false){
            seleccion = this.tipoGenetico.getSelectedIndex();
            bandera=true;
            String aux = this.tipoGenetico.getItemAt(seleccion);
            this.tipoGenetico.removeAllItems();
            this.tipoGenetico.addItem(aux);
        }
        
        if(seleccion==0){ //Binario
            
        } else if(seleccion==1){ //Reinas
            
        } else if(seleccion==2){ //SAT
            Matriz.matriz=Matriz.leerArchivo(1); //0: TSP, 1: SB
            String titulo= ("Genetico SAT " + this.numeroGenetico);
            Consola c = new Consola(titulo);
            this.geneticosSAT.add(this.numeroGenetico, new GeneticoSAT(900, 100000000, 0, 0, 0, 0, 0, 100, c));
            //tamaño de pobleación, num Generaciones, cuidad inicial o tamaño de tabl, 
            //prob Muta, seleccion para madre y padre, tipo de muestreo y tamaño de muestreo
            this.parametros.add(this.numeroGenetico, new Parametros(this.geneticosSAT.get(this.numeroGenetico), titulo));
            agregarItems(titulo);
            this.parametros.get(this.numeroGenetico).setVisible(true);
            this.numeroGenetico++;
        }else{ //TSP
            Matriz.matriz=Matriz.leerArchivo(0); //0: TSP, 1: SB
            String titulo= ("Genetico TSP " + this.numeroGenetico);
            Consola c = new Consola(titulo);
            this.geneticosTSP.add(this.numeroGenetico, new GeneticoTSP(500, 100000000, 0, 0, 0, 0, 0, c));
            //int tamanioPoblacion, int numeroGeneraciones, double probabilidadMuta, int seleM, int seleP, int tipoMuestreo, float muestreo, Consola consola
            this.parametros.add(this.numeroGenetico, new Parametros(this.geneticosTSP.get(this.numeroGenetico), titulo));
            agregarItems(titulo);
            this.parametros.get(this.numeroGenetico).setVisible(true);
            this.numeroGenetico++;
        }
    }//GEN-LAST:event_crearNuevoGeneticoBtnActionPerformed

    private void agregarItems(String titulo) {
        this.geneticoCambiarMejor1.addItem(titulo);
        this.geneticoCambiarMejor2.addItem(titulo);
        this.geneticoCambiarParametros1.addItem(titulo);
        this.geneticoCambiarParametros2.addItem(titulo);
    }
    
    private void btnIntercambiarParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntercambiarParametrosActionPerformed
        //CAMBIAR PARAMETROS ENTRE GENETICOS
        //Binario=0, Reinas=1, SAT=2, TSP=3
        int seleccion1 = this.geneticoCambiarParametros1.getSelectedIndex()-1;
        int seleccion2 = this.geneticoCambiarParametros2.getSelectedIndex()-1;
        //A seleccion2 le mandamos lo de seleccion1
        if(seleccion1 != seleccion2){
            switch(seleccion){ //tipo de genetico
                case 0:
                    GeneticoBinario aux3 = this.geneticosBinario.get(seleccion1);
                    this.geneticosBinario.get(seleccion2).cambiarParametros(aux3.getTamanioPoblacion(), aux3.getProbabilidadMuta(), aux3.getSeleccionMadre(), aux3.getSeleccionPadre(), aux3.getTipoMuestreo(), aux3.getPorcentajeMuestreo());
                    this.parametros.get(seleccion2).actualizarValores(); //actualizar valores en el JFrame de parametros de ese genetico
                    
                    break;
                case 1:
                    GeneticoReinas aux2 = this.geneticosReinas.get(seleccion1);
                    this.geneticosReinas.get(seleccion2).cambiarParametros(aux2.getTamanioPoblacion(), aux2.getProbabilidadMuta(), aux2.getSeleccionMadre(), aux2.getSeleccionPadre(), aux2.getTipoMuestreo(), aux2.getPorcentajeMuestreo());
                    this.parametros.get(seleccion2).actualizarValores(); //actualizar valores en el JFrame de parametros de ese genetico
                    
                    break;
                case 2:
                    GeneticoSAT aux = this.geneticosSAT.get(seleccion1);
                    this.geneticosSAT.get(seleccion2).cambiarParametros(aux.getTamanioPoblacion(), aux.getProbabilidadMuta(), aux.getSeleccionMadre(), aux.getSeleccionPadre(), aux.getTipoMuestreo(), aux.getPorcentajeMuestreo());
                    this.parametros.get(seleccion2).actualizarValores(); //actualizar valores en el JFrame de parametros de ese genetico
                        break;
                default :
                    GeneticoTSP aux1 = this.geneticosTSP.get(seleccion1);
                    this.geneticosTSP.get(seleccion2).cambiarParametros(aux1.getTamanioPoblacion(), aux1.getProbabilidadMuta(), aux1.getSeleccionMadre(), aux1.getSeleccionPadre(), aux1.getTipoMuestreo(), aux1.getPorcentajeMuestreo());
                    this.parametros.get(seleccion2).actualizarValores(); //actualizar valores en el JFrame de parametros de ese genetico
                        break;
            }
        }
    }//GEN-LAST:event_btnIntercambiarParametrosActionPerformed

    private void btnIntercambiarMejorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntercambiarMejorActionPerformed
        //MANDAT MEJOR INDIVISUO DE UN GENETICO A OTRO
        //Binario=0, Reinas=1, SAT=2, TSP=3
        int seleccion1 = this.geneticoCambiarMejor1.getSelectedIndex()-1;
        int seleccion2 = this.geneticoCambiarMejor2.getSelectedIndex()-1;
        //A seleccion2 le mandamos lo de seleccion1
        if(seleccion1 != seleccion2){
            switch(seleccion){ //tipo de genetico
                case 0:
                    GeneticoBinario aux1 = this.geneticosBinario.get(seleccion1);
                    //this.geneticosBinario.get(seleccion2).setMejorIndividuo(aux1.getMejorIndividuo());
                    
                    break;
                case 1:
                    GeneticoReinas aux2 = this.geneticosReinas.get(seleccion1);
                    //this.geneticosReinas.get(seleccion2).setMejorIndividuo(aux2.getMejorIndividuo());
                    
                    break;
                case 2:
                    GeneticoSAT aux3 = this.geneticosSAT.get(seleccion1);
                    this.geneticosSAT.get(seleccion2).setMejorIndividuo(aux3.getMejorIndividuo());
                            break;
                default :
                    GeneticoTSP aux4 = this.geneticosTSP.get(seleccion1);
                    this.geneticosTSP.get(seleccion2).setMejorIndividuo(aux4.getMejorIndividuo());
                    
                    break;
            }
        }
    }//GEN-LAST:event_btnIntercambiarMejorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIntercambiarMejor;
    private javax.swing.JButton btnIntercambiarParametros;
    private javax.swing.JButton crearNuevoGeneticoBtn;
    private javax.swing.JComboBox<String> geneticoCambiarMejor1;
    private javax.swing.JComboBox<String> geneticoCambiarMejor2;
    private javax.swing.JComboBox<String> geneticoCambiarParametros1;
    private javax.swing.JComboBox<String> geneticoCambiarParametros2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> tipoGenetico;
    // End of variables declaration//GEN-END:variables

}
